import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './media600px.css'
import './media1080px.css'
import { Provider } from 'components/ApolloProvider/Provider'
import { ShoppingCartProvider } from 'components/context/ShoppingCartProvider'
import * as React from "react";
import Script from 'next/script'
import Head from 'next/head'
import { ToastContainer } from 'react-toastify'
import { NotificationProvider } from 'components/context/NotificationContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Legitem',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href='/manifest.json' sizes="any" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"></meta> */}
      </head>
      <body className={inter.className}>
        <NotificationProvider>
        <ShoppingCartProvider>
        <Script
          type="module"
          src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
          strategy="lazyOnload"
        />
          <Provider>
            {children}
          </Provider>
        </ShoppingCartProvider>
        </NotificationProvider>
      </body>
    </html>
  )
}
