import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './media600px.css'
import './media1080px.css'
import { Provider } from 'components/ApolloProvider/Provider'
import { ShoppingCartProvider } from 'components/context/ShoppingCartProvider'
import * as React from "react";
import { NotificationProvider } from 'components/context/NotificationContext'
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Legitem',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <head>
        <link rel="manifest" href='/manifest.json' sizes="any" />
      </head>
      <body className={inter.className}>
        <NotificationProvider>
          <ShoppingCartProvider>
            <Provider>
              {children}
            </Provider>
          </ShoppingCartProvider>
        </NotificationProvider>
      </body>
    </html>
  )
}
